name: InnerTravelCoaching
favicon: null
layout_spectrum: 0.22758
typography_spectrum: 0.07831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0099a7'
    - '#fefefe'
    - '#c36524'
    - '#7b7855'
    - '#9fd8de'
  brandStrength: 1
  lightness: 0.007961639203131199
  saturation: 0.3481722993310541
  rhythmicContrast: 0.9260704657062888
purpose: []
