typography_spectrum: 0.07831
color:
  brandColors:
    - '#0099a7'
    - '#fefefe'
    - '#c36524'
    - '#7b7855'
    - '#9fd8de'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.3481722993310541
  rhythmicContrast: 0.9260704657062888
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.22758
analytics:
  google: null
  facebook: null
  twitter: null
name: InnerTravelCoaching
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: 'Get unstuck, get on your path, and go for it!'
purpose: []
